apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-ytt-templating
  annotations:
    render.crossplane.io/runtime: Development
    render.crossplane.io/runtime-development-target: localhost:9443